app/about/urls.py
from django.conf.urls import url

from about import views


urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
]

app/blog/urls.py
from django.conf.urls import url

from blog import views

urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^(?P<slug>[\w\-]+)/$', views.Post.as_view(), name='post')
]

app/experience/urls.py
from django.conf.urls import url

from experience import views

urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
]

app/ianclark/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from sitemaps import StaticViewSitemap

from blog.sitemaps import BlogIndexSitemap, BlogPostSitemap
from ianclark.views import AcmeChallenge


admin.autodiscover()

sitemaps = {
    'static': StaticViewSitemap,
    'blog_index': BlogIndexSitemap,
    'blog_posts': BlogPostSitemap,
}

urlpatterns = [
    url(r'.well-known/acme-challenge/(?P<certbot_id>.+$)',
        AcmeChallenge.as_view(),
        name='acme-challenge'),
    url(r'^', include('about.urls', namespace='about')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^experience/', include('experience.urls', namespace='experience')),
    url(r'^admin/', include(admin.site.urls)),
    url(
        r'^sitemap\.xml$',
        sitemap,
        {'sitemaps': sitemaps}
    ),
]

app/blog/models.py
from bs4 import BeautifulSoup

from django.db import models
from django.core.urlresolvers import reverse


class Post(models.Model):
    title = models.CharField("Blog title", max_length=255)
    slug = models.SlugField("Slug (unique)", max_length=255, primary_key=True)
    description = models.CharField(
        "Description", max_length=255, blank=True)
    tags = models.CharField(
        "Tags (Comma separated)", max_length=150, blank=True)
    created = models.DateTimeField("Creation date", auto_now_add=True)
    published = models.BooleanField("Published", default=True)

    # We store both the markdown content and the generated HTML for caching
    content = models.TextField()
    content_processed = models.TextField()

    class Meta:
        ordering = ['-created']

    def __unicode__(self):
        return self.title

    def get_excerpt(self):
        """
        Return an excerpt of the article's content.
        """
        if self.content_processed:
            soup = BeautifulSoup(self.content_processed)

            for tag in soup.findAll(True):
                if (
                    tag.name == "table" and
                    "code-snippettable" in tag.get("class", [])
                ):
                    tag.decompose()
                elif tag.name:
                    tag.unwrap()

            description = " ".join(soup.prettify().split())

            if len(description) > 252:
                return description[:252] + "..."
            else:
                return description

    def get_absolute_url(self):
        return reverse('blog:post', args=(self.slug,))

    @property
    def tags_filtered(self):
        return filter(None, self.tags.split(","))

app/blog/forms.py
from blog.models import Post
from django import forms
from wmd.widgets import WMDWidget


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=WMDWidget())

    class Meta:
        model = Post
        exclude = ()

app/about/views.py
from django.views.generic import TemplateView


class Index(TemplateView):
    template_name = 'about/index.html'

    def get_context_data(self):
        return dict(site_section='about')

app/blog/views.py
from django.views.generic import DetailView, ListView

from blog import models as blog_models


class Index(ListView):
    """
    List all published blog posts.
    """
    template_name = 'blog/index.html'
    queryset = blog_models.Post.objects.filter(published=True)
    context_object_name = 'posts'

    def get_context_date(self):
        return dict(page_title='Blog')


class Post(DetailView):
    """
    Display an individual blog post.
    """
    template_name = 'blog/post.html'

    def get_queryset(self):
        posts = blog_models.Post.objects.all()

        if 'show_unpub' in self.request.GET:
            return posts
        else:
            return posts.filter(published=True)

app/experience/views.py
from django.views.generic import TemplateView


class Index(TemplateView):
    template_name = 'experience/index.html'

    def get_context_data(self):
        return dict(
            page_title="Experience",
            active_section="experience")

app/ianclark/views.py
from django.conf import settings
from django.http import Http404, HttpResponse
from django.views.generic import View


class AcmeChallenge(View):
    def get(self, *args, **kwargs):
        if settings.CERTBOT_ID == kwargs['certbot_id']:
            return HttpResponse(settings.CERTBOT_KEY)
        else:
            raise Http404

app/about/templates/about/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block outermain %}
<main id="about-page" class="space-none" itemscope
      itemtype="http://schema.org/Person">
  <section id="about-greetings">
    <div class="wrapper">
      <div class="section-focal">
        <img id="picture-me" src="{% static 'img/me.jpg' %}" alt="Picture of me"
             itemprop="image" />
      </div>
      <div class="section-content">
        <h1>
          &ldquo;Hi, I'm <span itemprop="givenName">Ian</span>,
          thanks for visting.&rdquo;
        </h1>
        <p>
          Hello and welcome to my web site. My name's
          <span itemprop="name">
            Ian <span itemprop="familyName">Clark</span>
          </span>,
          and I'm a web developer from the
          <span itemprop="nationality">UK</span>.

          I currently work for the Home Cleaning Startup,
          {% spaceless %}
            <a href="https://housekeep.com/" itemprop="worksFor"
               target="_blank">
              <span>Housekeep</span>
            </a>,
          {% endspaceless %}
          as a <span itemprop="jobTitle">Lead software engineer</span>.
          My role requires a strong knowledge of
          <em>Python (Django) and JavaScript (AngularJS)</em>,
          and I have
          <a href="{% url 'experience:index' %}">
            experience in a number of other languages and technologies
          </a>.
          <strong>
            The aims of this site are twofold:
          </strong>
          to document my hobbies and skills, and to deliver useful resources
          from which others
          can learn.
          <strong>
            <a href="https://github.com/evenicoulddoit/IanClark.me"
               target="_blank">
              <i class="fa fa-github"></i>
              View the codebase on GitHub.
            </a>
          </strong>
        </p>
      </div>
    </div>
  </section>
  <section class="chapter">
    <div class="wrapper chapter-inside">
      <div class="section-focal">
        <img id="focal-code" src="{% static 'img/code-snippet.png' %}"
             alt="Snippet of code" />
      </div>
      <div class="section-content">
        <h1>My passion for web development</h1>
        <p>
          I began developing websites at the age of 14, in 2005. My initial
          static templates quickly evolved into dynamic and interactive content,
          and before long, I found myself
          <a href="{% static 'img/eicdi-tutorials.png' %}" target="_blank">
            developing educational content which received millions of hits
          </a>,
          and which was being cited as a pre-requisite for university modules.
          Shortly after completing my GCSEs, I was even
          <a href="{% static 'img/2008-paper.jpg' %}" target="_blank">
            featured in a local newspaper
          </a>
          for developing an impartial electronic reviews website
          <span class="note">(highly photogenic!)</span>.
        </p>
        <p>
          Whilst my skills have progressed considerably since my teenage years,
          I'm still as excited as I ever have been to deliver experiences which
          users love, and to
          <a href="//stackoverflow.com/users/1773904/" target="_blank">
            help others develop a similar passion
          </a>.
        </p>
      </div>
    </div>
  </section>
  <section class="chapter">
    <div class="wrapper chapter-inside">
      <div class="section-focal">
        <img src="{% static 'img/photography.jpg' %}"
             alt="Image of Amsterdam" />
      </div>
      <div class="section-content">
        <h1>Other interests</h1>
        <p>
          I'm actually a graduate in Economics, achieving a First-class degree
          from Loughborough University. I chose to study Economics, because I'm
          particularly interested in both its
          <a href="//amazon.co.uk/dp/0007256531/" target="_blank">
            behavioural
          </a>
          and welfare aspects. I also love science and listening to podcasts,
          such as
          <a href="//www.radiolab.org/" target="_blank">RadioLab</a>,
          <a href="//www.wnyc.org/shows/freakonomics-radio/" target="_blank">
            Freakonomics
          </a>
          and
          <a href="//www.npr.org/programs/ted-radio-hour/" target="_blank">
            TED
          </a>.
        </p>
        <p>
          Outside of academia, I'm interested in world news, photography
          (though not especially good at it), and sports such as football,
          weightlifting and badminton.
        </p>
      </div>
    </div>
  </section>
</main>
{% endblock %}

app/blog/templates/blog/index.html
{% extends "base.html" %}

{% block main %}
  <h1>Blog</h1>
  <section id="blog-listings" itemscope itemtype="http://schema.org/Blog">
    {% if not posts %}
      No posts found
    {% endif %}
    {% for post in posts %}
      <article class="blog-listing" itemscope itemtype="http://schema.org/BlogPosting">
        <div class="blog-keyfacts">
          <h2 class="blog-title" itemprop="headline">
            <a href="{{ post.get_absolute_url }}">
              {{ post.title }}
            </a>
          </h2>
          <time class="blog-date" itemprop="dateCreated"
                datetime="{{ post.created|date:'c' }}">
            {{ post.created|date:"M d, Y" }}
          </time>
        </div>
        <summary class="blog-excerpt">
          <p>{{ post.description }}</p>
        </summary>
        {% if post.tags_filtered %}
        <div class="blog-tags" itemprop="keywords">
          {% for tag in post.tags_filtered %}
            <div class="blog-tag">{{ tag }}</div>
          {% endfor %}
        </div>
        {% endif %}
      </article>
    {% endfor %}
  </section>
{% endblock %}

app/blog/templates/blog/post.html
{% extends "base.html" %}
{% load blog_markdown %}
{% load staticfiles %}

{% block main %}
  <article id="blog-post" itemscope itemtype="http://schema.org/BlogPosting">
    <div id="post-overview">
      <div id="post-author" itemscope itemtype="http://schema.org/Person" itemprop="author">
        <meta itemprop="givenName" content="Ian">
        <meta itemprop="familyName" content="Clark">
        <meta itemprop="nationality" content="British">
        <a href="{% url 'about:index' %}">
          <img alt="Picture of the author" src="{% static 'img/me.jpg' %}" itemprop="image" />
        </a>
      </div>
      <div id="post-keyfacts">
        <h1 id="post-title" itemprop="headline">{{ post.title }}</h1>
        <div id="post-date">
          Posted on:
          <time itemprop="dateCreated"
                datetime="{{ post.created|date:'Y-m-d\TH:i:s+00:00' }}">
            {{ post.created|date:"M d, Y" }}
          </time>
        </div>
      </div>
    </div>
    <div id="post-content" itemprop="articleBody">
      {{ post.content_processed|safe }}
    </div>
    <div id="post-tags" itemprop="keywords">
      {% for tag in post.get_tags %}
        <div class="blog-tag">{{ tag }}</div>
      {% endfor %}
    </div>
  </article>
{% endblock %}

app/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html itemscope itemtype="http://schema.org/WebPage" lang="en" dir="ltr">
  <head>
    {% with home_url="http://www.ianclark.me" default_title="Home" default_description="Personal website of web developer Ian Clark." %}
      <title>{{ page_title|default:default_title }} - Ian Clark</title>
      <meta charset="UTF-8">

      {% if page_url %}
        <link rel="canonical" href="{{home_url}}{{ page_url }}" />
        <meta property="og:url" content="{{home_url}}{{ page_url }}">
        <meta name="twitter:url" content="{{home_url}}{{ page_url }}">
      {% endif %}

      <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
      <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">

      <meta property="description" content="{{ page_description|default:default_description}}">

      <meta name="google-site-verification" content="RFByqKCpmOXdENVPPiIpb07oaXsyWl_3AceSMcwzfHM" />

      <meta property="og:title" content="{{ page_title|default:default_title }} - Ian Clark">
      <meta property="og:type" content="website">
      <meta property="og:image" content="{{home_url}}{% static 'img/logo-square-large.png' %}">
      <meta property="og:site_name" content="IanClark.me">
      <meta property="fb:admins" content="evenicoulddoit">

      <meta name="twitter:card" content="{{ page_description|default:default_description}}">
      <meta name="twitter:description" content="{{ page_description|default:default_description}}">
      <meta name="twitter:image" content="{{home_url}}{% static 'img/logo-square-twitter.png' %}">
      <meta name="twitter:title"
            content="{{ page_title|default:default_title|slice:':59' }} - Ian Clark">

      <meta itemprop="name" content="{{ page_title|default:default_title }} - Ian Clark">
      <meta itemprop="description" content="{{ page_description|default:default_description}}">
      <meta itemprop="image" content="{{home_url}}{% static 'img/logo-square-large.png' %}">

      <link href="{% static 'css/main.css' %}" rel="stylesheet">
      <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css"
            rel="stylesheet">
      {% block stylesheets %}{% endblock %}
    {% endwith %}
  </head>
  <body>
    <div id="footer-fix">
      {% block header %}
      <header>
        <div class="wrapper">
          <h1 id="logo" itemscope itemtype="http://schema.org/Person">
            <a href="/" itemprop="name">
              <span class="name-part" itemprop="givenName">Ian</span> <strong class="name-part" itemprop="familyName">Clark</strong>
            </a>
          </h1>
          <nav id="nav">
            <a id="nav-toggle" class="fa fa-bars"></a>
            <ul>
              <li>
                <a href="{% url 'blog:index' %}"
                   {% if site_section == 'blog' %}class="active"{% endif %}>
                  Blog
                </a>
              </li>
              <li>
                <a href="{% url 'experience:index' %}"
                   {% if site_section == 'experience' %}class="active"{% endif %}>
                  Experience
                </a>
              </li>
            </ul>
          </nav>
          <ul id="socials">
            <li>
              <a id="social-fb" href="//facebook.com/evenicoulddoit"
                 class="fa fa-facebook" target="_blank"></a>
            </li>
            <li>
              <a id="social-twitter" href="//twitter.com/evenicoulddoit"
                 class="fa fa-twitter" target="_blank"></a>
            </li>
            <li>
              <a id="social-google-plus" href="https://plus.google.com/106899359900878576772?rel=author"
                 class="fa fa-google-plus" target="_blank">Google</a>
            </li>
            <li>
              <a id="social-linkedin"
                 href="https://uk.linkedin.com/in/ian-clark-3b931543"
                 class="fa fa-linkedin" target="_blank"></a>
            </li>
            <li>
              <a id="social-github" href="//github.com/evenicoulddoit"
                 class="fa fa-github-alt" target="_blank"></a>
            </li>
            <li>
              <a id="social-so" href="//stackoverflow.com/users/1773904"
                 class="fa fa-stack-overflow" target="_blank"></a>
            </li>
          </ul>
        </div>
        <div id="header-divider">
          <div class="swatch-1"></div>
          <div class="swatch-2"></div>
          <div class="swatch-3"></div>
          <div class="swatch-4"></div>
        </div>
      </header>
      {% endblock %}
      {% block outermain %}
      <main>
        <div class="wrapper">
          {% block main %}{% endblock %}
        </div>
      </main>
      {% endblock %}
    </div>
    <footer>
      <div class="wrapper">
        <strong>IanClark.me</strong>
      </div>
    </footer>
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
    <script src="{% static 'js/main.min.js' %}"></script>
    {% block scripts %}{% endblock %}
  </body>
</html>